-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 19:19:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `idowner` INT NOT NULL,
  PRIMARY KEY (`idowner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL,
  `owner_idowner` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`, `owner_idowner`),
  INDEX `fk_user_owner1_idx` (`owner_idowner` ASC) VISIBLE,
  CONSTRAINT `fk_user_owner1`
    FOREIGN KEY (`owner_idowner`)
    REFERENCES `mydb`.`owner` (`idowner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idcustomer`, `user_iduser`),
  INDEX `fk_customer_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_customer_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `user_iduser` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `schedule` VARCHAR(45) NOT NULL,
  `joinDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_iduser`),
  CONSTRAINT `fk_staff_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `mydb`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `idmenu` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idorder` INT NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  `customer_user_iduser` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  `orderAmount` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `orderType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idorder`, `customer_idcustomer`, `customer_user_iduser`, `menu_idmenu`),
  INDEX `fk_order_customer1_idx` (`customer_idcustomer` ASC, `customer_user_iduser` ASC) VISIBLE,
  INDEX `fk_order_menu1_idx` (`menu_idmenu` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_idcustomer` , `customer_user_iduser`)
    REFERENCES `mydb`.`customer` (`idcustomer` , `user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `mydb`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservation` (
  `idreservation` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `reservation-number` VARCHAR(45) NOT NULL,
  `customer_idcustomer` INT NOT NULL,
  `customer_user_iduser` INT NOT NULL,
  `tableNumber` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  `guest` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idreservation`, `customer_idcustomer`, `customer_user_iduser`),
  INDEX `fk_reservation_customer1_idx` (`customer_idcustomer` ASC, `customer_user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_customer1`
    FOREIGN KEY (`customer_idcustomer` , `customer_user_iduser`)
    REFERENCES `mydb`.`customer` (`idcustomer` , `user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `idsalary` INT NOT NULL,
  `staff_user_iduser` INT NOT NULL,
  PRIMARY KEY (`idsalary`, `staff_user_iduser`),
  INDEX `fk_salary_staff1_idx` (`staff_user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_salary_staff1`
    FOREIGN KEY (`staff_user_iduser`)
    REFERENCES `mydb`.`staff` (`user_iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orderItem` (
  `idorderItem` INT NOT NULL,
  `menuItem` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `order_idorder` INT NOT NULL,
  `order_customer_idcustomer` INT NOT NULL,
  `order_customer_user_iduser` INT NOT NULL,
  `order_menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idorderItem`, `order_idorder`, `order_customer_idcustomer`, `order_customer_user_iduser`, `order_menu_idmenu`),
  INDEX `fk_orderItem_order1_idx` (`order_idorder` ASC, `order_customer_idcustomer` ASC, `order_customer_user_iduser` ASC, `order_menu_idmenu` ASC) VISIBLE,
  CONSTRAINT `fk_orderItem_order1`
    FOREIGN KEY (`order_idorder` , `order_customer_idcustomer` , `order_customer_user_iduser` , `order_menu_idmenu`)
    REFERENCES `mydb`.`order` (`idorder` , `customer_idcustomer` , `customer_user_iduser` , `menu_idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
